export function MahjongPath() {
const imagePath = {
    m1: require("../assets/images/mahjong/Man1.png"),
    m2: require("../assets/images/mahjong/Man2.png"),
    m3: require("../assets/images/mahjong/Man3.png"),
    m4: require("../assets/images/mahjong/Man4.png"),
    m5: require("../assets/images/mahjong/Man5.png"),
    m6: require("../assets/images/mahjong/Man6.png"),
    m7: require("../assets/images/mahjong/Man7.png"),
    m8: require("../assets/images/mahjong/Man8.png"),
    m9: require("../assets/images/mahjong/Man9.png"),
    m0: require("../assets/images/mahjong/Man5-Dora.png"),
    p1: require("../assets/images/mahjong/Pin1.png"),
    p2: require("../assets/images/mahjong/Pin2.png"),
    p3: require("../assets/images/mahjong/Pin3.png"),
    p4: require("../assets/images/mahjong/Pin4.png"),
    p5: require("../assets/images/mahjong/Pin5.png"),
    p6: require("../assets/images/mahjong/Pin6.png"),
    p7: require("../assets/images/mahjong/Pin7.png"),
    p8: require("../assets/images/mahjong/Pin8.png"),
    p9: require("../assets/images/mahjong/Pin9.png"),
    p0: require("../assets/images/mahjong/Pin5-Dora.png"),
    s1: require("../assets/images/mahjong/Sou1.png"),
    s2: require("../assets/images/mahjong/Sou2.png"),
    s3: require("../assets/images/mahjong/Sou3.png"),
    s4: require("../assets/images/mahjong/Sou4.png"),
    s5: require("../assets/images/mahjong/Sou5.png"),
    s6: require("../assets/images/mahjong/Sou6.png"),
    s7: require("../assets/images/mahjong/Sou7.png"),
    s8: require("../assets/images/mahjong/Sou8.png"),
    s9: require("../assets/images/mahjong/Sou9.png"),
    s0: require("../assets/images/mahjong/Sou5-Dora.png"),
    z1: require("../assets/images/mahjong/Ton.png"),
    z2: require("../assets/images/mahjong/Nan.png"),
    z3: require("../assets/images/mahjong/Shaa.png"),
    z4: require("../assets/images/mahjong/Pei.png"),
    z5: require("../assets/images/mahjong/Haku.png"),
    z6: require("../assets/images/mahjong/Hatsu.png"),
    z7: require("../assets/images/mahjong/Chun.png"),
    };
    return imagePath;
}